### ISSUE TITLE
undefining sprintf/snprintf

### ISSUE THREAD

**Issue by ikruglov** [h2o/qrintf#20]
Hi,

This is issue is not an issue, but a question.

What is the reason of redefining sprintf/snprintf to _qp_sprintf/_qp_snprintf which are not defined?
Is it a bug or is it supposed to be so?

I bumped to this matter because I want to use qrintf for hotspots and keep using sprintf for "regular" cases where simplicity and clearness matters more then speed.

With this block in qrintf.h I'm getting "undefined symbol: _qp_snprintf" error in runtime.

```
#undef sprintf
#define sprintf(...) _qp_sprintf(__VA_ARGS__)
#undef snprintf
#define snprintf(...) _qp_snprintf(__VA_ARGS__)
```

**Comment by kazuho** [comment]
`_qp_sprintf` and `_qp_snprintf` are markers that are recognized by the `qrintf-pp` command.  The command rewrites the invocations of the functions by inline-expanding their arguments; that is how qrintf optimizes sprintf and snprintf.

The reason why use `#define` for renaming `sprintf` (and `snprintf`) to the ones prefixed with `_qp_` is to prevent them from being rewritten by the header files of the standard library.  For example, glibc has its own defines for `sprintf` and `snprintf` designed to detect or mitigate misuse of the functions.

**Comment by ikruglov** [comment]
I don't need this thing anymore since I switched to tailor-made sprintf. But, you might want to add a possibility to disable un-definition of sprintf macros to allow one to use qrintf for hotspots and keep using sprintf as later has more understandable syntax.
P.S. Auto replacement by qrintf-pp is not always suitable.

**Comment by ikruglov** [comment]
btw, thanks for clarification!
